// src/modules/expenses/constants/expenseMockData.ts
import type { Expense } from "../components/Allexpensespanel";

export const MOCK_EXPENSES: Expense[] = [
  {
    id: "1",
    expenseNo: "EXP-2026-042",
    date: "2026-05-04",
    vendor: "TN Electricity Board",
    description: "Monthly electricity bill — April",
    category: "Utilities",
    amount: 18500,
    gstAmount: 2000,
    paymentMode: "BANK",
    status: "PAID",
  },
  {
    id: "2",
    expenseNo: "EXP-2026-041",
    date: "2026-05-04",
    vendor: "Indian Oil Pump",
    description: "Diesel for delivery vehicle TN 09 AB 1234",
    category: "Vehicle & Fuel",
    amount: 3200,
    paymentMode: "UPI",
    status: "PAID",
  },
  {
    id: "3",
    expenseNo: "EXP-2026-040",
    date: "2026-05-03",
    vendor: "Murugan Salt Suppliers",
    description: "Industrial salt for RO plant — 500kg",
    category: "Plant Operations",
    amount: 4500,
    gstAmount: 220,
    paymentMode: "CASH",
    status: "APPROVED",
  },
  {
    id: "4",
    expenseNo: "EXP-2026-039",
    date: "2026-05-03",
    vendor: "Saravanan Caps & Seals",
    description: "Bottle caps (500 units) + shrink wrap",
    category: "Packaging",
    amount: 2800,
    gstAmount: 100,
    paymentMode: "UPI",
    status: "PENDING",
  },
  {
    id: "5",
    expenseNo: "EXP-2026-038",
    date: "2026-05-02",
    vendor: "Plant Maintenance — Kumar",
    description: "RO membrane replacement labor",
    category: "Repairs",
    amount: 1500,
    paymentMode: "CASH",
    status: "PAID",
  },
  {
    id: "6",
    expenseNo: "EXP-2026-037",
    date: "2026-05-01",
    vendor: "Sundaram Property",
    description: "Plant rent for May 2026",
    category: "Rent & Lease",
    amount: 12000,
    paymentMode: "BANK",
    status: "PAID",
  },
  {
    id: "7",
    expenseNo: "EXP-2026-036",
    date: "2026-04-30",
    vendor: "Local Stationery",
    description: "Bills, receipts, and office supplies",
    category: "Office",
    amount: 850,
    paymentMode: "CASH",
    status: "PAID",
  },
];
