import React from "react";
import {
  HiOutlineLightningBolt,
  HiOutlineTruck,
  HiOutlineCube,
  HiOutlineOfficeBuilding,
  HiOutlineArchive,
  HiOutlineFolder,
  HiOutlineClipboardCheck,
  HiOutlineSpeakerphone,
  HiOutlineCreditCard,
} from "react-icons/hi";
import { HiOutlineWrench } from "react-icons/hi2";

// Use the shared type from the module's types file — do NOT redefine it here,
// otherwise TS treats the two ExpenseCategory shapes as incompatible.
import type { ExpenseCategory } from "../types/Expenses";

export const MOCK_CATEGORIES: ExpenseCategory[] = [
  {
    id: "1",
    name: "Utilities",
    description: "Electricity, water bill, internet",
    icon: React.createElement(HiOutlineLightningBolt, { size: 22 }),
    color: "#d97706",
    bg: "#fffbeb",
    spent: 22500,
    budget: 25000,
    transactions: 4,
    trend: 8,
  },
  {
    id: "2",
    name: "Vehicle & Fuel",
    description: "Diesel, vehicle service, FASTag",
    icon: React.createElement(HiOutlineTruck, { size: 22 }),
    color: "#2563eb",
    bg: "#eff6ff",
    spent: 18000,
    budget: 25000,
    transactions: 12,
    trend: -3,
  },
  {
    id: "3",
    name: "Plant Operations",
    description: "RO membrane, filters, salt, chemicals",
    icon: React.createElement(HiOutlineCube, { size: 22 }),
    color: "#0891b2",
    bg: "#ecfeff",
    spent: 14200,
    budget: 15000,
    transactions: 8,
    trend: 12,
  },
  {
    id: "4",
    name: "Rent & Lease",
    description: "Plant rent, godown, vehicle lease",
    icon: React.createElement(HiOutlineOfficeBuilding, { size: 22 }),
    color: "#4f46e5",
    bg: "#eef2ff",
    spent: 12000,
    budget: 12000,
    transactions: 1,
    trend: 5,
  },
  {
    id: "5",
    name: "Packaging",
    description: "Caps, seals, labels, shrink wrap",
    icon: React.createElement(HiOutlineArchive, { size: 22 }),
    color: "#7c3aed",
    bg: "#f5f3ff",
    spent: 7800,
    budget: 10000,
    transactions: 6,
    trend: -10,
  },
  {
    id: "6",
    name: "Repairs",
    description: "Equipment repair, vehicle maintenance",
    icon: React.createElement(HiOutlineWrench, { size: 22 }),
    color: "#ea580c",
    bg: "#fff7ed",
    spent: 4500,
    budget: 8000,
    transactions: 3,
    trend: -10,
  },
  {
    id: "7",
    name: "Office",
    description: "Stationery, tea, miscellaneous",
    icon: React.createElement(HiOutlineFolder, { size: 22 }),
    color: "#0d9488",
    bg: "#f0fdfa",
    spent: 3200,
    budget: 5000,
    transactions: 9,
    trend: 2,
  },
  {
    id: "8",
    name: "Compliance",
    description: "GST, BIS, FSSAI, pollution board",
    icon: React.createElement(HiOutlineClipboardCheck, { size: 22 }),
    color: "#dc2626",
    bg: "#fef2f2",
    spent: 2300,
    budget: 5000,
    transactions: 2,
    trend: 0,
  },
  {
    id: "9",
    name: "Marketing",
    description: "Pamphlets, hoardings, ads",
    icon: React.createElement(HiOutlineSpeakerphone, { size: 22 }),
    color: "#db2777",
    bg: "#fdf2f8",
    spent: 0,
    budget: 5000,
    transactions: 0,
    trend: 0,
  },
  {
    id: "10",
    name: "Loan",
    description: "EMI payments, interest charges",
    icon: React.createElement(HiOutlineCreditCard, { size: 22 }),
    color: "#e11d48",
    bg: "#fff1f2",
    spent: 0,
    budget: 0,
    transactions: 0,
    trend: 0,
  },
];

export const MONTHLY_BUDGET = {
  spent: 84500,
  total: 110000,
};
