import { Customer, Invoice, PaymentEntry, Product } from "../types/billing";

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: "1",
    name: "Rajesh Kumar",
    customerId: "CUS-001",
    phone: "+91 98765 43210",
    email: "rajesh@example.com",
    type: "Residential",
    status: "Active",
    outstanding: 1250,
    address: "12, Anna Nagar, Chennai - 600040",
    depositJars: 3,
    depositCans: 5,
    lastPaymentDate: "20 Apr 2026",
    overdueDays: 5,
    pricing: [
      {
        productId: "p1",
        productName: "20L Water Can",
        unit: "Per Can",
        basePrice: 40,
        customerPrice: 35,
        effectiveDate: "01 Jan 2026",
      },
      {
        productId: "p2",
        productName: "5L Water Jar",
        unit: "Per Jar",
        basePrice: 25,
        customerPrice: 22,
        effectiveDate: "01 Jan 2026",
      },
    ],
  },
  {
    id: "2",
    name: "Priya Sharma",
    customerId: "CUS-002",
    phone: "+91 87654 32109",
    email: "priya.s@example.com",
    type: "Residential",
    status: "Active",
    outstanding: 0,
    address: "45, T Nagar, Chennai - 600017",
    depositJars: 2,
    depositCans: 3,
    lastPaymentDate: "25 Apr 2026",
    overdueDays: 0,
    pricing: [],
  },
  {
    id: "3",
    name: "Chennai IT Park Pvt Ltd",
    customerId: "CUS-003",
    phone: "+91 44 2345 6789",
    email: "admin@chennaitp.com",
    type: "Commercial",
    status: "Active",
    outstanding: 18500,
    address: "Lot 5, Tidel Park, Taramani, Chennai - 600113",
    depositJars: 0,
    depositCans: 50,
    lastPaymentDate: "10 Apr 2026",
    overdueDays: 15,
    pricing: [
      {
        productId: "p1",
        productName: "20L Water Can",
        unit: "Per Can",
        basePrice: 40,
        customerPrice: 30,
        effectiveDate: "01 Jan 2026",
      },
    ],
  },
  {
    id: "4",
    name: "Murugan Enterprises",
    customerId: "CUS-004",
    phone: "+91 98123 45678",
    email: "murugan@example.com",
    type: "Industrial",
    status: "Active",
    outstanding: 45000,
    address: "Plot 23, Ambattur Industrial Estate, Chennai - 600058",
    depositJars: 0,
    depositCans: 100,
    lastPaymentDate: "01 Apr 2026",
    overdueDays: 24,
    pricing: [
      {
        productId: "p1",
        productName: "20L Water Can",
        unit: "Per Can",
        basePrice: 40,
        customerPrice: 28,
        effectiveDate: "01 Jan 2026",
      },
      {
        productId: "p3",
        productName: "1L Water Bottle (Pack of 12)",
        unit: "Per Pack",
        basePrice: 120,
        customerPrice: 100,
        effectiveDate: "01 Jan 2026",
      },
    ],
  },
  {
    id: "6",
    name: "Arun Hotels & Restaurants",
    customerId: "CUS-006",
    phone: "+91 98765 11223",
    email: "arun.hotels@example.com",
    type: "Commercial",
    status: "Active",
    outstanding: 3200,
    address: "22, Mount Road, Chennai - 600002",
    depositJars: 0,
    depositCans: 25,
    lastPaymentDate: "18 Apr 2026",
    overdueDays: 7,
    pricing: [
      {
        productId: "p1",
        productName: "20L Water Can",
        unit: "Per Can",
        basePrice: 40,
        customerPrice: 32,
        effectiveDate: "01 Mar 2026",
      },
      {
        productId: "p2",
        productName: "5L Water Jar",
        unit: "Per Jar",
        basePrice: 25,
        customerPrice: 20,
        effectiveDate: "01 Mar 2026",
      },
    ],
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "p1",
    name: "20L Water Can",
    sku: "WC-20L",
    unit: "Per Can",
    basePrice: 40,
    stock: 250,
    category: "Cans",
  },
  {
    id: "p2",
    name: "5L Water Jar",
    sku: "WJ-5L",
    unit: "Per Jar",
    basePrice: 25,
    stock: 180,
    category: "Jars",
  },
  {
    id: "p3",
    name: "1L Water Bottle (Pack of 12)",
    sku: "WB-1L-12",
    unit: "Per Pack",
    basePrice: 120,
    stock: 95,
    category: "Bottles",
  },
  {
    id: "p4",
    name: "500ml Water Bottle (Pack of 24)",
    sku: "WB-500-24",
    unit: "Per Pack",
    basePrice: 150,
    stock: 60,
    category: "Bottles",
  },
  {
    id: "p5",
    name: "2L Water Bottle (Pack of 6)",
    sku: "WB-2L-6",
    unit: "Per Pack",
    basePrice: 90,
    stock: 120,
    category: "Bottles",
  },
  {
    id: "p6",
    name: "10L Water Can",
    sku: "WC-10L",
    unit: "Per Can",
    basePrice: 25,
    stock: 100,
    category: "Cans",
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: "inv1",
    invoiceNo: "INV-20260425-001",
    customerId: "CUS-001",
    customerName: "Rajesh Kumar",
    customerType: "Residential",
    customerPhone: "+91 98765 43210",
    customerAddress: "12, Anna Nagar, Chennai - 600040",
    items: [
      {
        product: "20L Water Can",
        qty: 10,
        price: 35,
        total: 350,
        sku: "WC-20L",
      },
    ],
    subtotal: 350,
    gst: 0,
    discount: 0,
    grandTotal: 350,
    paidAmount: 350,
    balanceAmount: 0,
    status: "Paid",
    paymentMode: "Cash",
    deliveryMode: "Delivery",
    date: "25 Apr 2026",
    time: "9:15 AM",
    notes: "Regular weekly order",
  },
  {
    id: "inv2",
    invoiceNo: "INV-20260425-002",
    customerId: "CUS-003",
    customerName: "Chennai IT Park Pvt Ltd",
    customerType: "Commercial",
    customerPhone: "+91 44 2345 6789",
    items: [
      {
        product: "20L Water Can",
        qty: 50,
        price: 30,
        total: 1500,
        sku: "WC-20L",
      },
    ],
    subtotal: 1500,
    gst: 270,
    discount: 0,
    grandTotal: 1770,
    paidAmount: 1770,
    balanceAmount: 0,
    status: "Paid",
    paymentMode: "UPI",
    deliveryMode: "Delivery",
    date: "25 Apr 2026",
    time: "10:30 AM",
    notes: "",
  },
  {
    id: "inv3",
    invoiceNo: "INV-20260425-003",
    customerId: "CUS-004",
    customerName: "Murugan Enterprises",
    customerType: "Industrial",
    customerPhone: "+91 98123 45678",
    items: [
      {
        product: "20L Water Can",
        qty: 100,
        price: 28,
        total: 2800,
        sku: "WC-20L",
      },
      {
        product: "1L Water Bottle (Pack of 12)",
        qty: 10,
        price: 100,
        total: 1000,
        sku: "WB-1L-12",
      },
    ],
    subtotal: 3800,
    gst: 684,
    discount: 200,
    grandTotal: 4284,
    paidAmount: 0,
    balanceAmount: 4284,
    status: "Pending",
    paymentMode: "Credit",
    deliveryMode: "Delivery",
    date: "25 Apr 2026",
    time: "11:45 AM",
    notes: "Monthly bulk order",
  },
  {
    id: "inv5",
    invoiceNo: "INV-20260424-008",
    customerId: "CUS-006",
    customerName: "Arun Hotels & Restaurants",
    customerType: "Commercial",
    customerPhone: "+91 98765 11223",
    items: [
      {
        product: "20L Water Can",
        qty: 25,
        price: 32,
        total: 800,
        sku: "WC-20L",
      },
      { product: "5L Water Jar", qty: 10, price: 20, total: 200, sku: "WJ-5L" },
    ],
    subtotal: 1000,
    gst: 180,
    discount: 0,
    grandTotal: 1180,
    paidAmount: 600,
    balanceAmount: 580,
    status: "Partial",
    paymentMode: "UPI",
    deliveryMode: "Delivery",
    date: "24 Apr 2026",
    time: "11:20 AM",
    notes: "Partial payment received",
  },
  {
    id: "inv6",
    invoiceNo: "INV-20260422-005",
    customerId: "CUS-001",
    customerName: "Rajesh Kumar",
    customerType: "Residential",
    customerPhone: "+91 98765 43210",
    items: [
      {
        product: "20L Water Can",
        qty: 10,
        price: 35,
        total: 350,
        sku: "WC-20L",
      },
      { product: "5L Water Jar", qty: 5, price: 22, total: 110, sku: "WJ-5L" },
    ],
    subtotal: 460,
    gst: 0,
    discount: 10,
    grandTotal: 450,
    paidAmount: 0,
    balanceAmount: 450,
    status: "Overdue",
    paymentMode: "Credit",
    deliveryMode: "Delivery",
    date: "22 Apr 2026",
    time: "9:00 AM",
    notes: "",
  },
];

export const INITIAL_PAYMENTS: PaymentEntry[] = [
  {
    id: "pay1",
    paymentNo: "PAY-20260425-001",
    invoiceNo: "INV-20260425-001",
    customerId: "CUS-001",
    customerName: "Rajesh Kumar",
    amount: 350,
    mode: "Cash",
    date: "25 Apr 2026",
    time: "9:20 AM",
    reference: "",
    notes: "Full payment",
  },
  {
    id: "pay2",
    paymentNo: "PAY-20260425-002",
    invoiceNo: "INV-20260425-002",
    customerId: "CUS-003",
    customerName: "Chennai IT Park Pvt Ltd",
    amount: 1770,
    mode: "UPI",
    date: "25 Apr 2026",
    time: "10:35 AM",
    reference: "UPI-REF-78945",
    notes: "",
  },
  {
    id: "pay3",
    paymentNo: "PAY-20260424-005",
    invoiceNo: "INV-20260424-008",
    customerId: "CUS-006",
    customerName: "Arun Hotels & Restaurants",
    amount: 600,
    mode: "UPI",
    date: "24 Apr 2026",
    time: "11:25 AM",
    reference: "UPI-REF-66321",
    notes: "Partial payment",
  },
];

export const COMPANY_INFO = {
  name: "Balaji Aqua",
  tagline: "Pure Water · Pure Trust",
  address: "12, Industrial Estate, Ambattur, Chennai - 600058",
  phone: "+91 44 2625 8899",
  email: "contact@balajiaqua.com",
  gstin: "33AABCB1234C1Z5",
  fssai: "12345678901234",
};
