
import type { UamUser, UamCompany } from "../types/Uam";

export const DUMMY_COMPANIES: UamCompany[] = [
  { id: "c1", name: "Balaji Aqua Water Plant", type: "WATER_PLANT" },
  { id: "c2", name: "Chennai Beverages Co", type: "BEVERAGE" },
];

export const DUMMY_USERS: UamUser[] = [
  {
    id: "u1",
    firstName: "Devaa",
    lastName: "Balaji",
    email: "devaa@balajiaqua.com",
    phone: "9876543210",
    role: "SUPER_ADMIN",
    isActive: true,
    createdAt: "2026-01-15T09:00:00.000Z",
    userCompanies: [],
  },
  {
    id: "u2",
    firstName: "Ramesh",
    lastName: "Kumar",
    email: "ramesh@balajiaqua.com",
    phone: "9876500001",
    role: "ADMIN",
    isActive: true,
    createdAt: "2026-02-01T09:00:00.000Z",
    userCompanies: [{ company: DUMMY_COMPANIES[0] }],
  },
  {
    id: "u3",
    firstName: "Priya",
    lastName: "Sundaram",
    email: "priya@chennaibeverages.com",
    phone: "9876500002",
    role: "ADMIN",
    isActive: true,
    createdAt: "2026-02-10T09:00:00.000Z",
    userCompanies: [{ company: DUMMY_COMPANIES[1] }],
  },
  {
    id: "u4",
    firstName: "Suresh",
    lastName: "M",
    email: "suresh@balajiaqua.com",
    phone: "9876500003",
    role: "STAFF",
    isActive: true,
    createdAt: "2026-03-05T09:00:00.000Z",
    userCompanies: [{ company: DUMMY_COMPANIES[0] }],
  },
  {
    id: "u5",
    firstName: "Lakshmi",
    lastName: "N",
    email: "lakshmi@chennaibeverages.com",
    phone: "9876500004",
    role: "STAFF",
    isActive: false,
    createdAt: "2026-03-20T09:00:00.000Z",
    userCompanies: [{ company: DUMMY_COMPANIES[1] }],
  },
  {
    id: "u6",
    firstName: "Vijay",
    lastName: "Anand",
    email: "vijay@balajiaqua.com",
    phone: "9876500005",
    role: "DELIVERY_BOY",
    isActive: true,
    createdAt: "2026-04-02T09:00:00.000Z",
    userCompanies: [{ company: DUMMY_COMPANIES[0] }],
  },
  {
    id: "u7",
    firstName: "Karthik",
    lastName: "R",
    email: "karthik@chennaibeverages.com",
    phone: "9876500006",
    role: "DELIVERY_BOY",
    isActive: true,
    createdAt: "2026-05-11T09:00:00.000Z",
    userCompanies: [{ company: DUMMY_COMPANIES[1] }],
  },
];
